name: Docker Image Test Run

on:
  push:
    branches: [ master ]
 
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose -f "docker-compose.yml" build

      - name: Run DB setup
        run: docker-compose run web rails db:setup

      - name: Run Tests
        run: docker-compose run web rspec

      - name: Deploy Coverage to GH Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: coverage # The folder the action should deploy.

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
